# === workflow_settings.yaml ===
dataformCoreVersion: 3.0.2          # Ajusta si usas otra versión
defaultProject: spring-line-421422
defaultLocation: europe-west1
defaultDataset: analytics_297430230 # Solo un valor por defecto
defaultAssertionDataset: superform_assertions

vars: # Variables que variarás por país/entorno
  GA4_DATASET:           analytics_297430230   # Paraguay por defecto
  OUTPUTS_DATASET:       Data_Paraguay_Processed
  TRANSFORMATIONS_DATASET: Data_Paraguay_Processed_transformations
  QUALITY_DATASET:       Data_Paraguay_Processed_quality
  LOCAL_TIMEZONE:        America/Asuncion
