# === workflow_settings.yaml ===
defaultProject: pga-data-b2b-marketing-dev
defaultLocation: europe-west1
defaultDataset: analytics_297430230  # Solo un valor por defecto
defaultAssertionDataset: superform_assertions


vars: # Variables que variarás por país/entorno
  GA4_DATASET:           analytics_297430230  # Paraguay por defecto
  OUTPUTS_DATASET:       superform_outputs_297430230
  TRANSFORMATIONS_DATASET: superform_transformations_297430230
  QUALITY_DATASET:       superform_quality_297430230
  LOCAL_TIMEZONE:        America/Asuncion
  LABEL_GENERIC_BRAND:   prosegur_global
  LABEL_EXECUTION_OPERATION: manual_workflow