# This file contains settings for all workflow configurations.
# It replaces the deprecated dataform.json.

defaultProject: spring-line-421422
defaultLocation: europe-west1
defaultAssertionDataset: superform_assertions

# Global variables applicable to all workflows unless overridden.
vars:
  LABEL_EXECUTION_OPERATION: "manual_workflow"
  LABEL_GENERIC_BRAND: "prosegur"
  LABEL_GENERIC_LICENSE_TYPE: "core"
  LABEL_GENERIC_PACKAGE_VERSION: "v1-17-0"
  LABEL_GENERIC_TOOL: "ga4dataform"

# Defines different workflow configurations (e.g., for development, production per country).

  # Development environment configuration
  development:
    vars:
      GA4_DATASET: analytics_297430230 # Default to Paraguay for development
      OUTPUTS_DATASET: dev_outputs
      TRANSFORMATIONS_DATASET: dev_transformations
      QUALITY_DATASET: dev_quality
      LOCAL_TIMEZONE: America/Asuncion

  # Production configurations per country
  Paraguay:
    vars:
      GA4_DATASET: "analytics_297430230"
      OUTPUTS_DATASET: "Data_Paraguay_Processed"
      TRANSFORMATIONS_DATASET: "Data_Paraguay_Processed_transformations"
      QUALITY_DATASET: "Data_Paraguay_Processed_quality"
      LOCAL_TIMEZONE: "America/Asuncion"

  Argentina:
    vars:
      GA4_DATASET: "analytics_297153875"
      OUTPUTS_DATASET: "Data_Argentina_Processed"
      TRANSFORMATIONS_DATASET: "Data_Argentina_Processed_transformations"
      QUALITY_DATASET: "Data_Argentina_Processed_quality"
      LOCAL_TIMEZONE: "America/Argentina/Buenos_Aires"

  Chile:
    vars:
      GA4_DATASET: "analytics_297349390"
      OUTPUTS_DATASET: "Data_Chile_Processed"
      TRANSFORMATIONS_DATASET: "Data_Chile_Processed_transformations"
      QUALITY_DATASET: "Data_Chile_Processed_quality"
      LOCAL_TIMEZONE: "America/Santiago"

  Uruguay:
    vars:
      GA4_DATASET: "analytics_297377934"
      OUTPUTS_DATASET: "Data_Uruguay_Processed"
      TRANSFORMATIONS_DATASET: ""
      QUALITY_DATASET: "Data_Uruguay_Processed_quality"
      LOCAL_TIMEZONE: "America/Montevideo"