defaultAssertionDataset: superform_assertion_297430230
defaultDataset: superform_outputs_297430230
defaultLocation: EU
defaultProject: pga-data-b2b-marketing-dev
vars:
  GA4_DATASET: analytics_297430230
  LABEL_EXECUTION_OPERATION: daily_workflow
  LABEL_GENERIC_BRAND: superformlabs
  LABEL_GENERIC_LICENSE_TYPE: core
  LABEL_GENERIC_PACKAGE_VERSION: v1-17-0
  LABEL_GENERIC_TOOL: ga4dataform
  LOCAL_TIMEZONE: Europe/Brussels
  OUTPUTS_DATASET: superform_outputs_297430230
  QUALITY_DATASET: superform_quality_297430230
  TRANSFORMATIONS_DATASET: superform_transformations_297430230
