# This file contains settings for the default development environment.
# Production configurations are managed in dataform.json

defaultProject: spring-line-421422
defaultLocation: europe-west1

# Default variables for development compilations.
# These can be overridden by the compilations in dataform.json.
vars:
  GA4_DATASET: analytics_297430230 # Default to Paraguay for development
  OUTPUTS_DATASET: dev_outputs
  TRANSFORMATIONS_DATASET: dev_transformations
  QUALITY_DATASET: dev_quality
  LOCAL_TIMEZONE: America/Asuncion

